### ISSUE TITLE
Package not found error on start

### ISSUE THREAD

**Issue by kunduarnab** [michaeltroger/template-matching-android#2]
When I try to open the app , a popup apears and it says "package not found, opencv manager was not found! Try to install it?"

**Comment by michaeltroger** [comment]
Apologies! I totally lost track over this repo over the years.

Probably your question is no longer relevant for you but I thought I will answer in case anybody else encounters this:
 [OpenCV Manager](https://play.google.com/store/apps/details?id=org.opencv.engine) needs to be installed in version 1.
Usually even in version 1 there should have been a popup dialog asking you to install this app from the Play Store.
Maybe your device has no Google Play services installed?

However with the version 1.1 that I just published the OpenCv Manager is included anyways - it includes the entire OpenCV so no additional app has to be installed.
